modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "sonariaworld"
version = "${version}"
displayName = "Sonaria World"
authors = ""
description = '''

'''
#logoFile = ""

[[dependencies.sonariaworld]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sonariaworld]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11,)"
ordering = "NONE"
side = "BOTH"


[[mixins]]
config = "sonariaworld.mixins.json"
